---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: app-env
  namespace: pocketbase-auth
spec:
  encryptedData:
    SERVICE_URL_APP: AgCipyzUR4VIBITbHD/UOOAoMRTLZojftOrV5hcItI/e3h2o4cgLzCW/4KXg9gn9x35BVFVl1ntnzTm+JvJIztWnTelc6juwt+jGn2k5+6T5ZQvL+HPk1kgXkEoxQnYOIvWzqsXbtyYHmVlJ3yFvo7/gAHLBiktqrPhHZkOlWUaNat8PGggj92yr8+RuFTNBIYxSAdcU13SXO45EsWH64FZBo0Npu4MKXzLl+h8vfDb8dgQvXhcN8DZzvT25HBTZ6l1Ul+sKnPRkDGCsb6qaIoKyuHzNEPPJxMoQ9d0sYD3fIAMLNw165O+BkGt2eH6gH3PZ5wY6FDw9/hRX+f5jgSujhCSFwgvyKqdhWg7dSzFzFylYK2RoU0jeamvwdhyArc1tJpZ5oPphMgA2rPJibQQKTZ+fCri+woM27M51TZ767xwLh8EEXnaNEaatYvMLVZ4cPzh+Pf6tL5EiiHrRLGCnql0+HHn2gHxglXIOr+Ig3agIr6v34XDN7HW3MPD6mMmmR9U9Dgo7NHl5GLslpOs9ZwaPmCd0POVewDxx0NWYbaTz+mE43nqN40WU5a+VhKDdKED+fUzVciuMaYg2LYGJr8bbYF7JvQgfCz8E4PaSPl7O+1SKHzGQO9DSuoQ/tNjAjs9ESKgkE/UF2A4mJt3IPZXxDUTz3I1kfDD1qTqsMRp53WHvO/Ic2+1jEYDvlf5Wdu+5RdBWSqmHC9ImvsKU8+2O5Sci+GJCneGxA5ISh0gTmniOJw==
    SERVICE_URL_AUTH: AgCgZPsCbm+t0NP3XFvPvrj/RCmoYljFQUzgGmeie+FHap/JAMB3lW5rQqN1dNXLKi9gl9DxQKFGfmDw618zZ94kdLSrFqVCZpAdO3JUazskiDrzN4wXeizR7MBqAGyp4l4ry73tkUeMgWKEg7ff5h9PdlWvGRyjLt/MYBJ2zq7ztKb+rypZY2whTZuMs3M4ahhxSRr8hpLG5jL8snZTxtbOshi8E48qaLjjQp2dtyCkR+CuEGp9QK30RbQeQRi78WItk83XPUDibDuz5gdTkve4WhnNzgFqJZTYYwfTIpC4vaL4yvFUFDkEXkgabOyuj+zRSfD4NYXplzKsunl68B8S0jYGrsYroYR4UyWCwa4xtUs/H2JHDJN+0sodCV7NwfsVvzvkUPQxiSGUh60ZdAne3PyJItO+IsJoShJqm34S1fqIzY80oXbSwbwf5ukI7eT51hPHPZdokRs252BBJ6dDRUYU6B4JTW1c6ws/tB8vis5S+NRM7CNXFzqevUalIqtXWw/H5ielemvgC/q26G7uY8y085y1vWpfrFtzie19JmY4Z9YI1XS4A6Gz61oAdmLepBcF189fp1719ceFucgff7snRPs4dxYZAtaC8e6x5EvYjR8qt7v+PVlJk+cAhrpBp/TqXyWD4MepgX0ZDz1xS+LI9rxFqWSqYPcfY9fokF3NVfG6zlSPggUZBLTOM0Zu7PJdrSZYvUHP0nrKhgt00JLoAJ/U2xkRfPOsyXHSy2n9+tWio6UjWJE+
  template:
    metadata:
      creationTimestamp: null
      name: app-env
      namespace: pocketbase-auth
